### ISSUE TITLE
fix: very_good create flutter_app doesn't create RunnerTests on iOS

### ISSUE THREAD

**Issue by omartinma** [VeryGoodOpenSource/very_good_cli#766]
**Description**
It seems that new versions of Flutter require an iOS profile called RunnerTests. Not sure what is the implication of this new profile but it is being called on Podfile

**Steps To Reproduce**

1. Create new app with `very_good create flutter_app my_app`.
2. Observe that RunnerTests is missing inside ios folder.
3. Also if running the project this error appears 

>  [!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find `Runner`

**Expected Behavior**
RunnerTests should be on ios folder, same than running flutter create

<img width="303" alt="image" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/11978998/258ef9b8-1e31-42b8-99da-a4e7f3fe109e">

**Comment by cofirazak** [comment]
same for me

**Comment by fabiomlferreira** [comment]
I have the same problem

**Comment by renancaraujo** [comment]
Tracking fix on https://github.com/VeryGoodOpenSource/very_good_core/pull/285

**Comment by renancaraujo** [comment]
This should be fixed in the new CLI version

**Comment by yuruyuri16** [comment]
@renancaraujo I tried the latest version by just adding firebase_core and the error still shows up. 😥

**Comment by miguelangelflores1993** [comment]
I have the same problem

**Comment by yuruyuri16** [comment]
The problem is still there. I do not know much about Xcode but I believe that the RunnerTests directory has not being linked correctly.

The left side show a project created with flutter create and the right side uses the very good cli.

<img width="912" alt="Screenshot 2023-12-10 at 00 30 08" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/36353498/6e5f3bc0-8ce7-4c35-9205-92b7166f7b51">

**Comment by ItsAlexousd** [comment]
I have the same error with a freshly created project (latest CLI version).

**Comment by alestiago** [comment]
Thank you for your patience @yuruyuri16 and @ItsAlexousd.

This hasn't been released within Very Good CLI yet, but it has been released on Brickhub. If you would like to generate using the Brickhub release you can follow the [instructions in the Brickhub website](https://brickhub.dev/bricks/very_good_core/0.5.0#changelog).

We aim to be releasing Very Good CLI soon, which will include the fix.

**Comment by alestiago** [comment]
As a heads up, Very Good CLI 0.19.0 has now been released. Generating a flutter_app should run successfully in iOS again 🙌 💙 

(cc: @yuruyuri16 , @ItsAlexousd )
